"""add default value for candidate status

Revision ID: 08df0d4ca88b
Revises: 9f3fe1233934
Create Date: 2026-09-20 00:28:14.168056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08df0d4ca88b"
down_revision: Union[str, Sequence[str], None] = "9f3fe1233934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidates", sa.Column("status", sa.String(length=255), nullable=False)
    )
    op.create_index(
        op.f("ix_candidates_status"), "candidates", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidates_status"), table_name="candidates")
    op.drop_column("candidates", "status")
    # ### end Alembic commands ###
