"""add timestamps to user roles

Revision ID: 294d1deb6ab4
Revises: 66e703f9ede1
Create Date: 2026-09-21 23:51:31.912827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "294d1deb6ab4"
down_revision: Union[str, Sequence[str], None] = "66e703f9ede1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_roles",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "user_roles",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_roles", "updated_at")
    op.drop_column("user_roles", "created_at")
    # ### end Alembic commands ###
