"""add type to candidates

Revision ID: 344d3d154dfe
Revises: f66bdb9eaaef
Create Date: 2026-09-08 22:23:56.279210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344d3d154dfe'
down_revision: Union[str, Sequence[str], None] = 'f66bdb9eaaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_candidates_type'), 'candidates', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_type'), table_name='candidates')
    op.drop_column('candidates', 'type')
    # ### end Alembic commands ###
