"""add unique constraint for role

Revision ID: 490c4cc5d89e
Revises: a49f9bed5574
Create Date: 2026-09-21 11:37:50.642180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "490c4cc5d89e"
down_revision: Union[str, Sequence[str], None] = "a49f9bed5574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "roles", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles", type_="unique")
    # ### end Alembic commands ###
