"""add key to role

Revision ID: 66e703f9ede1
Revises: 490c4cc5d89e
Create Date: 2026-09-21 15:42:35.024220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e703f9ede1'
down_revision: Union[str, Sequence[str], None] = '490c4cc5d89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('key', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_roles_key'), 'roles', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_key'), table_name='roles')
    op.drop_column('roles', 'key')
    # ### end Alembic commands ###
