"""add unique constraint to permission

Revision ID: 99e1b75d3186
Revises: 4a059bab1645
Create Date: 2026-09-22 11:03:47.565436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99e1b75d3186"
down_revision: Union[str, Sequence[str], None] = "4a059bab1645"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=False)
    # ### end Alembic commands ###
