"""add experience, type to candidates

Revision ID: b7f46e4757ad
Revises: 344d3d154dfe
Create Date: 2026-09-09 00:19:30.030135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f46e4757ad'
down_revision: Union[str, Sequence[str], None] = '344d3d154dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('experience', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'experience')
    # ### end Alembic commands ###
