"""add interview data to recruitment steps

Revision ID: cb7568bb60ae
Revises: 1b08b4cf1fda
Create Date: 2026-09-16 22:56:18.949554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7568bb60ae'
down_revision: Union[str, Sequence[str], None] = '1b08b4cf1fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruitment_steps', sa.Column('interview_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruitment_steps', 'interview_date')
    # ### end Alembic commands ###
