"""add interviewer to recruitment step

Revision ID: f509f679cbd9
Revises: a9203513c924
Create Date: 2026-09-20 16:10:41.755458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f509f679cbd9"
down_revision: Union[str, Sequence[str], None] = "a9203513c924"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruitment_steps", sa.Column("interviewer_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "recruitment_steps", "users", ["interviewer_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recruitment_steps", type_="foreignkey")
    op.drop_column("recruitment_steps", "interviewer_id")
    # ### end Alembic commands ###
