services:
  postgres:
    image: postgres:18
    container_name: recruitment-postgres
    restart: unless-stopped
  
    environment:
      POSTGRES_USER: recruitment
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recruitment

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: